apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-game
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web-game
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web-game
        image: myfirstproject.azurecr.io/images/my-nodejs-test:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
       - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: web-game
  namespace: test
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web-game